# 广播机制

对两个形状相同的NDArray做按元素运算。当对两个形状不同的NDArray按元素运算时，可能会触发广播（broadcasting）机制：
先适当复制元素使这两个NDArray形状相同后再按元素运算

In [2]:
from mxnet import nd

In [3]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [4]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [5]:
A * B


[[0. 0.]
 [0. 1.]
 [0. 2.]]
<NDArray 3x2 @cpu(0)>

# 索引

索引的位置行、列都是从0开始，左闭右开

In [11]:
x = nd.arange(12)
X = x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

指定了NDArray的行索引截取范围[1:3]。依据左闭右开指定范围的惯例，它截取了矩阵X中行索引为1和2的两行。

In [12]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

指定NDArray中需要访问的单个元素的位置，如矩阵中行和列的索引，并为该元素重新赋值。

In [14]:
X[2,2] = 9
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9.  9. 11.]]
<NDArray 3x4 @cpu(0)>

截取一部分元素，并为它们重新赋值。在下面的例子中，我们为行索引为1的每一列元素重新赋值。

In [15]:
X[1:2,:] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9.  9. 11.]]
<NDArray 3x4 @cpu(0)>