In [1]:
from mxnet import nd

## 1、创建NDArray

### 用arange函数创建一个行向量

In [4]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

#### 通过shape属性来获取NDArray实例的形状

In [7]:
x.shape

(12,)

#### 通过size属性得到NDArray实例中元素（element）的总数

In [8]:
x.size

12

#### 用reshape函数把行向量x的形状改为(3, 4)，也就是一个3行4列的矩阵，并记作X

In [11]:
X = x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

#### 创建一个各元素为0，形状为(2, 3, 4)的张量。实际上，之前创建的向量和矩阵都是特殊的张量

In [12]:
o = nd.zeros((2,3,4))
o


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

#### 创建各元素为1的张量

In [13]:
y = nd.ones((3,4))
y


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

#### 通过Python的列表（list）指定需要创建的NDArray中每个元素的值

In [15]:
Y = nd.array([[2, 3, 4, 1], [3, 1, 4, 3], [2, 5, 1, 6]])
Y


[[2. 3. 4. 1.]
 [3. 1. 4. 3.]
 [2. 5. 1. 6.]]
<NDArray 3x4 @cpu(0)>

#### 随机生成NDArray中每个元素的值。下面我们创建一个形状为(3, 4)的NDArray。它的每个元素都随机采样于均值为0、标准差为1的正态分布

In [17]:
v = nd.random.normal(0,1, shape=(3,4))
v


[[-0.68106437 -0.1353156   0.37723133  0.41016456]
 [ 0.5712682  -2.7579627   1.07628    -0.6141325 ]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

## 2、运算

#### 加法

In [19]:
X + Y


[[ 2.  4.  6.  4.]
 [ 7.  6. 10. 10.]
 [10. 14. 11. 17.]]
<NDArray 3x4 @cpu(0)>

#### 乘法

In [20]:
X * Y


[[ 0.  3.  8.  3.]
 [12.  5. 24. 21.]
 [16. 45. 10. 66.]]
<NDArray 3x4 @cpu(0)>

#### 除法

In [21]:
X / Y


[[ 0.          0.33333334  0.5         3.        ]
 [ 1.3333334   5.          1.5         2.3333333 ]
 [ 4.          1.8        10.          1.8333334 ]]
<NDArray 3x4 @cpu(0)>

#### 指数

In [22]:
Y.exp()


[[  7.389056   20.085537   54.59815     2.7182817]
 [ 20.085537    2.7182817  54.59815    20.085537 ]
 [  7.389056  148.41316     2.7182817 403.4288   ]]
<NDArray 3x4 @cpu(0)>

### 用dot进行加法计算

In [23]:
nd.dot(X,Y.T)


[[ 14.  18.  25.]
 [ 54.  62.  81.]
 [ 94. 106. 137.]]
<NDArray 3x3 @cpu(0)>

#### 可以将多个NDArray连结（concatenate）。下面分别在行上（维度0，即形状中的最左边元素）和列上（维度1，   
#### 即形状中左起第二个元素）连结两个矩阵。可以看到，输出的第一个NDArray在维度0的长度（ 6 ）为两个输入矩阵在维度0的长度之和（ 3+3 ），  
#### 而输出的第二个NDArray在维度1的长度（ 8 ）为两个输入矩阵在维度1的长度之和（ 4+4 ）

In [24]:
nd.concat(X,Y,dim=0),nd.concat(X,Y,dim=1)

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  3.  4.  1.]
  [ 3.  1.  4.  3.]
  [ 2.  5.  1.  6.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  3.  4.  1.]
  [ 4.  5.  6.  7.  3.  1.  4.  3.]
  [ 8.  9. 10. 11.  2.  5.  1.  6.]]
 <NDArray 3x8 @cpu(0)>)

#### 使用条件判断式可以得到元素为0或1的新的NDArray。
#### 以X == Y为例，如果X和Y在相同位置的条件判断为真（值相等），那么新的NDArray在相同位置的值为1；反之为0。

In [25]:
X == Y


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

#### 对NDArray中的所有元素求和得到只有一个元素的NDArray

In [26]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

#### 通过asscalar函数将结果变换为Python中的标量。
#### 下面例子中X的 L2 范数结果同上例一样是单元素NDArray，但最后结果变换成了Python中的标量。

In [30]:
X.norm().asscalar()

22.494442