In [1]:
from mxnet import nd

### 用arange函数创建一个行向量

In [4]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

#### 通过shape属性来获取NDArray实例的形状

In [7]:
x.shape

(12,)

#### 通过size属性得到NDArray实例中元素（element）的总数

In [8]:
x.size

12

#### 用reshape函数把行向量x的形状改为(3, 4)，也就是一个3行4列的矩阵，并记作X

In [11]:
X = x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

#### 创建一个各元素为0，形状为(2, 3, 4)的张量。实际上，之前创建的向量和矩阵都是特殊的张量

In [12]:
o = nd.zeros((2,3,4))
o


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

#### 创建各元素为1的张量

In [13]:
y = nd.ones((3,4))
y


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

#### 通过Python的列表（list）指定需要创建的NDArray中每个元素的值

In [15]:
Y = nd.array([[2, 3, 4, 1], [3, 1, 4, 3], [2, 5, 1, 6]])
Y


[[2. 3. 4. 1.]
 [3. 1. 4. 3.]
 [2. 5. 1. 6.]]
<NDArray 3x4 @cpu(0)>

#### 随机生成NDArray中每个元素的值。下面我们创建一个形状为(3, 4)的NDArray。它的每个元素都随机采样于均值为0、标准差为1的正态分布

In [17]:
v = nd.random.normal(0,1, shape=(3,4))
v


[[-0.68106437 -0.1353156   0.37723133  0.41016456]
 [ 0.5712682  -2.7579627   1.07628    -0.6141325 ]
 [ 1.8307649  -1.1468065   0.05383794 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>