In [1]:
from mxnet import nd

### 用arange函数创建一个行向量

In [4]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

#### 通过shape属性来获取NDArray实例的形状

In [7]:
x.shape

(12,)

#### 通过size属性得到NDArray实例中元素（element）的总数

In [8]:
x.size

12

#### 用reshape函数把行向量x的形状改为(3, 4)，也就是一个3行4列的矩阵，并记作X

In [11]:
X = x.reshape((3,4))
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>