# 广播机制

对两个形状相同的NDArray做按元素运算。当对两个形状不同的NDArray按元素运算时，可能会触发广播（broadcasting）机制：
先适当复制元素使这两个NDArray形状相同后再按元素运算

In [2]:
from mxnet import nd

In [4]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>,
 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [5]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [6]:
A * B


[[0. 0.]
 [0. 1.]
 [0. 2.]]
<NDArray 3x2 @cpu(0)>