# 运算的内存开销

使用Python自带的id函数：如果两个实例的ID一致，那么它们所对应的内存地址相同；反之则不同。

In [1]:
from mxnet import nd

In [2]:
x = nd.arange(12)
X = x.reshape((3, 4))
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [4]:
before = id(Y)
Y = Y + X
id(Y) == before

False

如果想指定结果到特定内存，我们可以使用前面介绍的索引来进行替换操作。在下面的例子中，我们先通过zeros_like创建和Y形状相同且元素为0的NDArray，记为Z。接下来，我们把X + Y的结果通过[:]写进Z对应的内存中。

In [5]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [6]:
Z


[[ 2.  3.  8.  9.]
 [ 9. 12. 15. 18.]
 [20. 21. 22. 23.]]
<NDArray 3x4 @cpu(0)>

实际上，上例中我们还是为X + Y开了临时内存来存储计算结果，再复制到Z对应的内存。如果想避免这个临时内存开销，我们可以使用运算符全名函数中的out参数。

In [7]:
nd.elemwise_add(X, Y, out=Z)
id(Z) == before

True

如果X的值在之后的程序中不会复用，我们也可以用 X[:] = X + Y 或者 X += Y 来减少运算的内存开销。

In [8]:
before = id(X)
X += Y
id(X) == before

True

# NDArray和NumPy相互变换

可以通过array函数和asnumpy函数令数据在NDArray和NumPy格式之间相互变换。下面将NumPy实例变换成NDArray实例。

In [9]:
import numpy as np

P = np.ones((2, 3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

再将NDArray实例变换成NumPy实例。

In [10]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)